# VexOS - Main desktop workstation configuration
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix
    
    # Core modules
    ../../modules/core
    
    # Desktop environment
    ../../modules/desktop
    
    # Hardware support
    ../../modules/hardware
    
    # Common packages
    ../../modules/packages
    
    # Flatpak support
    ../../modules/packages/flatpak.nix
    
    # GPU driver - uncomment the appropriate one:
    # ../../modules/hardware/nvidia.nix
    # ../../modules/hardware/amd.nix
    # ../../modules/hardware/intel.nix
  ];

  # Desktop-specific settings
  networking.hostName = "vex-os";
  
  # Desktop packages
  environment.systemPackages = with pkgs; [
    # Browsers
    firefox
    
    # Development
    vscode
    
    # Media
    vlc
  ];
  
  # Enable printing
  services.printing.enable = true;

  # System version - DO NOT CHANGE after initial install
  system.stateVersion = "24.11";
}
