# VexHTPC - Home Theater PC configuration
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix
    
    # Core modules
    ../../modules/core
    
    # Desktop environment
    ../../modules/desktop
    
    # Hardware support
    ../../modules/hardware
    
    # Common packages
    ../../modules/packages
    
    # Flatpak support
    ../../modules/packages/flatpak.nix
    
    # GPU driver - uncomment the appropriate one:
    # ../../modules/hardware/nvidia.nix
    # ../../modules/hardware/amd.nix
    # ../../modules/hardware/intel.nix
  ];

  # HTPC-specific settings
  networking.hostName = "vex-htpc";
  
  # HTPC packages
  environment.systemPackages = with pkgs; [
    # Media players
    vlc
    mpv
    
    # Remote control / Kodi
    # kodi
  ];
  
  # Enable SSH for remote management
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };
  
  # Open firewall for media streaming (optional)
  # networking.firewall.allowedTCPPorts = [ 8080 ];

  # System version - DO NOT CHANGE after initial install
  system.stateVersion = "24.11";
}
