# Hardware configuration for vex-htpc
# This file should be generated by nixos-generate-config
# and replaced with your actual hardware configuration
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # PLACEHOLDER: Replace this file with the output of:
  # sudo nixos-generate-config --show-hardware-config
  
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ]; # or kvm-amd for AMD CPUs
  
  # Filesystem mounts - MUST be configured for your system
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";  # Update this
    fsType = "ext4";                       # or btrfs, etc.
  };
  
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";   # Update this
    fsType = "vfat";
  };
  
  swapDevices = [ ];
  
  # Hardware-specific settings
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # Use this for AMD: hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
