# VexVM - Virtual Machine configuration
# Auto-detects hypervisor (QEMU/KVM, VirtualBox, VMware, Hyper-V)
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware configuration - imported from system's /etc/nixos/
    # This file is auto-generated by nixos-generate-config on each machine
    /etc/nixos/hardware-configuration.nix
    
    # Core modules
    ../../modules/core
    
    # Desktop environment
    ../../modules/desktop
    
    # Hardware support
    ../../modules/hardware
    
    # VM Guest auto-detection (QEMU, VirtualBox, VMware, Hyper-V)
    ../../modules/hardware/vm-guest.nix
    
    # Common packages
    ../../modules/packages
    
    # Flatpak support
    ../../modules/packages/flatpak.nix
  ];

  # VM-specific settings
  networking.hostName = "vex-vm";
  
  # VM packages
  environment.systemPackages = with pkgs; [
    # Useful VM tools
    pciutils
    usbutils
  ];
  
  # Enable SSH for remote management (useful for headless VMs)
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;  # Allow password auth for convenience in VMs
      PermitRootLogin = "no";
    };
  };
}
