# VexSVR - Server configuration
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware configuration - imported from system's /etc/nixos/
    # This file is auto-generated by nixos-generate-config on each machine
    /etc/nixos/hardware-configuration.nix
    
    # Core modules
    ../../modules/core
    
    # Hardware support (no desktop for server)
    ../../modules/hardware
    
    # Common packages
    ../../modules/packages
  ];

  # Server-specific settings
  networking.hostName = "vex-svr";
  
  # Disable NetworkManager on server, use systemd-networkd
  networking.networkmanager.enable = false;
  networking.useNetworkd = true;
  
  # Server packages
  environment.systemPackages = with pkgs; [
    # Server utilities
    tmux
    
    # Monitoring
    iotop
    nethogs
  ];
  
  # Enable SSH
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };
  
  # Open SSH port
  networking.firewall.allowedTCPPorts = [ 22 ];

  # System version - DO NOT CHANGE after initial install
  system.stateVersion = "24.11";
}
