# This is a template hardware configuration.
# You should replace this with your actual hardware-configuration.nix
# generated by NixOS installation or by running:
# sudo nixos-generate-config --show-hardware-config

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration - UPDATE THESE FOR YOUR SYSTEM
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # Add "kvm-intel" (Intel VT-x) or "kvm-amd" (AMD-V) here when running on real
  # hardware with hardware virtualization support enabled in the BIOS/UEFI.
  # Leave this empty (or omit it entirely) when running in a VM without nested
  # virtualization — loading kvm-intel/kvm-amd in a guest without VT-x access
  # prevents /dev/kvm from being created and causes libvirtd to fail on startup.
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Filesystems - UPDATE THESE FOR YOUR SYSTEM
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";  # Update this
    fsType = "ext4";
  };

  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-label/boot";  # Only needed for UEFI/ESP systems
  #   fsType = "vfat";
  # };

  # Swap - UPDATE OR REMOVE
  # swapDevices = [ 
  #   { device = "/dev/disk/by-label/swap"; }
  # ];

  # CPU Configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # For AMD: hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # ── VM-in-VM workaround ──────────────────────────────────────────────────────
  # Uncomment the block below ONLY if this machine is running NixOS inside a
  # hypervisor (e.g. VirtualBox) that lacks nested KVM support. Enabling this
  # globally in a module is a security risk — it disables QEMU DAC confinement.
  #
  # virtualisation.libvirtd.qemu.verbatimConfig = ''
  #   namespaces = []
  #   security_driver = "none"
  # '';

  # ── Bootloader ────────────────────────────────────────────────────────────
  # This template uses GRUB (legacy BIOS/MBR) so `nix flake check` passes
  # without requiring an EFI System Partition to be defined.
  #
  # On real hardware, replace with the appropriate config for your firmware:
  #
  # UEFI (systemd-boot — most modern hardware):
  #   Remove the three grub lines below and add:
  #   fileSystems."/boot" = { device = "/dev/disk/by-uuid/XXXX"; fsType = "vfat"; };
  #   (system.nix already enables systemd-boot via lib.mkDefault — nothing else needed)
  #
  # Legacy BIOS/MBR (GRUB):
  #   Keep the lines below and update the device path (check with `lsblk`).
  #
  # A plain assignment here overrides the lib.mkDefault in system.nix; no lib.mkForce needed.
  boot.loader.systemd-boot.enable  = false;
  boot.loader.grub.enable          = true;
  boot.loader.grub.device          = "/dev/sda";  # UPDATE: verify with `lsblk`
}
