# This is a template hardware configuration.
# You should replace this with your actual hardware-configuration.nix
# generated by NixOS installation or by running:
# sudo nixos-generate-config --show-hardware-config

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration - UPDATE THESE FOR YOUR SYSTEM
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];  # Change to "kvm-amd" for AMD processors
  boot.extraModulePackages = [ ];

  # Filesystems - UPDATE THESE FOR YOUR SYSTEM
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";  # Update this
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";  # Update this
    fsType = "vfat";
  };

  # Swap - UPDATE OR REMOVE
  # swapDevices = [ 
  #   { device = "/dev/disk/by-label/swap"; }
  # ];

  # CPU Configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # For AMD: hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
